import streamlit as st
import requests

# --------------------------------------------------
# CONFIG
# --------------------------------------------------
API_URL = "https://fraud-detection-fastapi-ouqr.onrender.com/predict"
HEALTH_URL = "https://fraud-detection-fastapi-ouqr.onrender.com/health"

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(
    page_title="Fraud Detection System",
    layout="centered"
)

# --------------------------------------------------
# HEADER
# --------------------------------------------------
st.title("💳 Fraud Detection System")
st.caption("Real-time transaction risk assessment using Machine Learning")

# --------------------------------------------------
# BACKEND HEALTH CHECK
# --------------------------------------------------
with st.spinner("Checking system status..."):
    try:
        health = requests.get(HEALTH_URL, timeout=3)
        if health.status_code == 200:
            st.success("🟢 Fraud Detection API is online")
        else:
            st.warning("🟡 API reachable but unhealthy")
    except Exception:
        st.error("🔴 Backend service is unavailable")

st.divider()

# --------------------------------------------------
# USER INPUTS (ONLY BUSINESS INPUTS)
# --------------------------------------------------
amount = st.number_input(
    "Transaction Amount (₹)",
    min_value=0.0,
    step=100.0,
    value=500.0
)

hour = st.slider(
    "Transaction Hour (0–23)",
    min_value=0,
    max_value=23,
    value=12
)

# --------------------------------------------------
# BUTTON ACTION
# --------------------------------------------------
if st.button("Check Fraud", disabled=(amount <= 0)):

    # 🔴 IMPORTANT FIX: SEND ALL 7 FEATURES
    payload = {
        "amount": float(amount),
        "hour": int(hour),

        # Default engineered features (match training)
        "feature_3": 1.0,
        "feature_4": 0.0,
        "feature_5": 0.5,
        "feature_6": 3.0,
        "feature_7": 0.0
    }

    try:
        response = requests.post(API_URL, json=payload, timeout=10)

        if response.status_code == 200:
            result = response.json()

            probability = result["probability"]
            risk = result["risk_level"]

            fraud_pct = round(probability * 100, 2)
            safe_pct = round((1 - probability) * 100, 2)

            # --------------------------------------------------
            # DECISION LOGIC
            # --------------------------------------------------
            if risk == "LOW":
                decision = "🟢 TRANSACTION APPROVED"
                action = "Proceed with transaction"
                color = st.success
            elif risk == "MEDIUM":
                decision = "🟡 REVIEW REQUIRED"
                action = "Perform OTP / manual verification"
                color = st.warning
            else:
                decision = "🔴 TRANSACTION BLOCKED"
                action = "Block and escalate to fraud team"
                color = st.error

            st.divider()

            st.subheader(decision)

            col1, col2, col3 = st.columns(3)
            col1.metric("Risk Level", risk)
            col2.metric("Fraud Probability", f"{fraud_pct}%")
            col3.metric("Confidence (Safe)", f"{safe_pct}%")

            st.subheader("🔍 Risk Factors")

            if amount >= 100000:
                st.write("⚠ High transaction amount")
            else:
                st.write("✔ Normal transaction amount")

            if hour < 6 or hour > 22:
                st.write("⚠ Unusual transaction timing")
            else:
                st.write("✔ Normal transaction timing")

            st.subheader("➡ Recommended Action")
            color(action)

        else:
            st.error(f"API Error ({response.status_code})")
            st.code(response.text)

    except requests.exceptions.Timeout:
        st.error("⏱ Request timed out")
    except requests.exceptions.ConnectionError:
        st.error("❌ Unable to reach backend service")
    except Exception as e:
        st.error("Unexpected error occurred")
        st.code(str(e))

# --------------------------------------------------
# DISCLAIMER
# --------------------------------------------------
st.divider()
st.caption(
    "⚠️ This output is generated by a machine learning model and is intended "
    "as a decision-support tool. Final decisions should follow business, risk, "
    "and compliance policies."
)